config/routes.rb
Rails.application.routes.draw do
  mount Newebpay::Engine => '/newebpay'
  # devise_for :admin_users, :controllers => { omniauth_callbacks: "admin_users/omniauth_callbacks" }
  ActiveAdmin.routes(self)
  # mount Ckeditor::Engine => '/ckeditor'
  
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = 'admin_users/omniauth_callbacks'
  devise_for :admin_users, devise_config

  root "welcome#index"
  get '/api', to: 'api#index'

  namespace :api do 
	  namespace :v1 do 
  		resources :candidates, :videos, :cities, only: [:index, :show]
  	end	
  end

  resources :donations, except: :index
  
end

app/models/donation.rb
class Donation < ApplicationRecord
  has_many :donation_items
  has_many :donation_rewards, through: :donation_items
  has_many :donation_categories, through: :donation_rewards
  
  belongs_to :donation_category
  enum donate_type: {
    person: 1,
    company: 2
  }
  enum receipt_type: {
    mailing: 0, #email收據
    paper: 1, #紙本收據
    no_receipt: 2 #不要收據
  }

  validates :total_amount, numericality: { only_integer: true, greater_than: 299, message: "捐款金額不得低於300" }, if: Proc.new{ |a| a.donation_category_id == 2 } 
  validates :name, presence: true, unless: :anonymous?
  validates :mobile_phone, presence: { message: "手機號碼不得為空" }, unless: :anonymous?
  validates :county, :district, presence: { message: "請選擇縣市區域" }
  validates :road, presence: true

  def set_total_amount
    self.total_amount = donation_items.sum(:amount) 
    self.save
  end

  def address
    "#{county}#{district}#{road}"
  end

end

# == Schema Information
#
# Table name: donations
#
#  id                   :bigint           not null, primary key
#  donation_category_id :bigint
#  name                 :string
#  citizend             :string
#  mobile_phone         :string
#  total_amount         :integer
#  description          :text
#  receipt_type         :integer
#  donate_type          :integer
#  confirmed            :boolean
#  confirmed_at         :datetime
#  anonymous            :boolean          default(FALSE)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  payment_type         :string
#  county               :string
#  district             :string
#  zipcode              :integer
#  road                 :string
#

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :find_donation, only: [:show, :edit, :update]

  def create
    @donation = Donation.new(donation_params)
 
    if @donation.save
      if @donation.donation_category_id == 1  #小物
        @donation_items = @donation.donation_items.new(donation_id: @donation.id, donation_reward_id: params[:donation][:donation_items][:donation_reward_id], quantity: params[:donation][:donation_items][:quantity])
        @donation_items.save!
        @donation.set_total_amount
      end
      cookies.encrypted[:donation_id] = { value: @donation.id, expires: 15.minutes.from_now }
    else
      redirect_to root_path, notice: "新增失敗"
    end
    
  end

  def show
  end

  def edit
  end

  def update
    if @donation.update(donation_params)
      if @donation.donation_category_id == 1  #小物
        @donation_items = @donation.donation_items.first
        @donation_items.quantity = params[:donation][:donation_items][:quantity].to_i
        @donation_items.save!
        @donation.set_total_amount
      end
      redirect_to donation_path(@donation)
    else
      render :edit
    end
    
  end

private
  def donation_params
    params.require(:donation).permit(
      :donation_category_id,
      :name,
      :mobile_phone,
      :total_amount,
      :road,
      :county,
      :district,
      :zipcode
    )
  end

  def address_params
    params.permit(:county, :district, :zipcode)
  end

  def find_donation
    @donation = Donation.find_by(id: cookies.encrypted[:donation_id])
    unless @donation
      flash[:error] = "很抱歉，該頁面已失效，請重新填寫。"
      redirect_to root_path
      return
    end
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<% count = 0 %>
    <% donation_commodity.donation_rewards.each do |reward| %>
      <h1><%= reward.heading %></h1>
      <%= simple_form_for @donation, :url => donations_path, :method => :post do |f| %>
        <%= f.input :donation_category_id, as: :hidden, input_html: {value: donation_commodity.id} %>
        <%= f.simple_fields_for :donation_items do |donation_item_form| %>
          <%= render "donations/donation_item", f: donation_item_form, reward: reward %>
        <% end %>
        <h3>收件人<%= f.input :name, placeholder: "王小明", required: true, label: false %></h3>
        <%= f.input :mobile_phone, placeholder: "0900321456" %>

        <h3>寄送地址</h3>
        <div id="twzipcode<%= count %>"><% count += 1 %>
          <%= f.select :county, html:{ 
            :'data-role' => "county",
            :'data-style'=> "Style Name",
            :'data-name'=> "donation[county]", 
            :'data-value'=> "110" 
            }%>
          <%= f.select :district, html:{ 
            :'data-role' => "district",
            :'data-style'=> "Style Name",
            :'data-name'=> "donation[district]", 
            :'data-value'=> "臺北市" 
            }%>
          
          <div class="hidden"
               data-role="zipcode"
               data-name="donation[zipcode]"
               >
          </div>
        </div>
        <%= f.input :road, placeholder: "杭州南路一段115號2樓之1", required: true, label: false %>
        <%= f.submit "立即付款贊助" %>
      <% end %>
    <% end %>
    <h1><%= donation_free.name %></h1>
    <%= simple_form_for @donation, :url => donations_path, :method => :post do |f| %>
      <%= f.input :donation_category_id, as: :hidden, input_html: {value: donation_free.id} %>

      <h3>贊助金額 <%= f.input :total_amount, placeholder: "500", required: true, label: false %></h3>
      <h3>收件人<%= f.input :name, placeholder: "王小明", required: true, label: false %></h3>
      <%= f.input :mobile_phone, placeholder: "0900321456" %>

      <h3>寄送地址</h3>
      <div id="twzipcode<%= count %>"><% count += 1 %>
        <%= f.select :county, html:{ 
          :'data-role' => "county",
          :'data-style'=> "Style Name",
          :'data-name'=> "donation[county]", 
          :'data-value'=> "110" 
          }%>
        <%= f.select :district, html:{ 
          :'data-role' => "district",
          :'data-style'=> "Style Name",
          :'data-name'=> "donation[district]", 
          :'data-value'=> "臺北市" 
          }%>
        
        <div class="hidden"
             data-role="zipcode"
             data-name="donation[zipcode]"
             >
        </div>
      </div>
      <%= f.input :road, placeholder: "杭州南路一段115號2樓之1", required: true, label: false %>
      <%= f.submit "立即付款贊助" %>
    <% end %>

<script language="JavaScript">

    // var citizen_id_selector = $("#donation_citizen_id");
   var county = $('.county').val();
   var district = $('.district').val();
   $(document).ready(function(){
     for(i=0; i < '<%= count %>'; i++){
       $(`#twzipcode${i}`).twzipcode({
        zipcodeIntoDistrict: true, // 郵遞區號自動顯示在區別選單中
        css: ["city form-control", "town form-control"], // 自訂 "城市"、"地別" class 名稱 
        countyName: county, // 自訂城市 select 標籤的 name 值
        districtName: district // 自訂區別 select 標籤的 name 值
        }
       );
     }
   });
 </script>
   

app/views/donations/_donation_item.html.erb
<%= f.input :donation_reward_id, as: :hidden, input_html: { value: reward.id } %>
<%= image_tag(reward.image.thumb.url, class: "img-responsive") if reward.image? %>
<h4 class="media-heading"><%= reward.name_amount%></h4>
<div class="">數量：<%= f.input :quantity, collection: 1..10, label: false, include_blank: "請選擇數量", input_html:{class: "require_select_one"} %></div>

app/views/donations/_form.html.erb
<% count = 0 %>

<% if donation.donation_category_id == 1 %>
  <% " 小物 " %>
  <h2><%= donation.donation_rewards.first.name %></h2>
  <%= simple_form_for donation do |f| %>
    <%= f.input :donation_category_id, as: :hidden, input_html: {value: donation.donation_category_id} %>
    <%= f.simple_fields_for :donation_items do |donation_item_form| %>
      <%= render "donations/donation_item", f: donation_item_form, reward: donation.donation_rewards.first %>
    <% end %>

    <h3>收件人<%= f.input :name, placeholder: "王小明", required: true, label: false %></h3>
    <%= f.input :mobile_phone, placeholder: "0900321456" %>
    
    <h3>寄送地址</h3>
    <div id="twzipcode<%= count %>"><% count += 1 %>
      <%= f.select :county, html:{ 
        :'data-role' => "county",
        :'data-style'=>"Style Name",
        :'data-name'=>"donation[county]", 
        :'data-value'=>"110" 
        }%>
      <%= f.select :district, html:{ 
        :'data-role' => "district",
        :'data-style'=>"Style Name",
        :'data-name'=>"donation[district]", 
        :'data-value'=>"臺北市" 
        }%>
      
      <div class="hidden"
           data-role="zipcode"
           data-name="donation[zipcode]"
           >
      </div>
    </div>
    <%= f.input :road, placeholder: "杭州南路一段115號2樓之1", required: true, label: false %>
    <%= f.submit "立即付款贊助" %>
  <% end %>
<% else %>
  <h1><%= donation.donation_category.name %></h1>
  <%= simple_form_for donation do |f| %>
    <%= f.input :donation_category_id, as: :hidden, input_html: {value: donation.donation_category.id} %>
  
    <h3>贊助金額 <%= f.input :total_amount, placeholder: "500", required: true, label: false %></h3>
    <h3>收件人<%= f.input :name, placeholder: "王小明", required: true, label: false %></h3>
    <%= f.input :mobile_phone, placeholder: "0900321456" %>

    <h3>寄送地址</h3>
    <div id="twzipcode<%= count %>"><% count += 1 %>
      <%= f.select :county, html:{ 
        :'data-role' => "county",
        :'data-style'=>"Style Name",
        :'data-name'=>"donation[county]", 
        :'data-value'=>"110" 
        }%>
      <%= f.select :district, html:{ 
        :'data-role' => "district",
        :'data-style'=>"Style Name",
        :'data-name'=>"donation[district]", 
        :'data-value'=>"臺北市" 
        }%>
      
      <div class="hidden"
           data-role="zipcode"
           data-name="donation[zipcode]"
           >
      </div>
    </div>
    <%= f.input :road, placeholder: "杭州南路一段115號2樓之1", required: true, label: false %>
    <%= f.submit "立即付款贊助" %>
  <% end %>
<% end %>
 



<script language="JavaScript">

    // var citizen_id_selector = $("#donation_citizen_id");
   var county = $('.county').val();
   var district = $('.district').val();
   $(document).ready(function(){
     for(i=0; i < '<%= count %>'; i++){
       $(`#twzipcode${i}`).twzipcode({
        zipcodeIntoDistrict: true, // 郵遞區號自動顯示在區別選單中
        css: ["city form-control", "town form-control"], // 自訂 "城市"、"地別" class 名稱 
        countyName: county, // 自訂城市 select 標籤的 name 值
        districtName: district // 自訂區別 select 標籤的 name 值
        });

       $(`#twzipcode${i}`).twzipcode('set', {
           'district': `<%= @donation.district %>`,
           'county': `<%= @donation.county %>`
        });

       $('#donation_donation_items_quantity').val(`<%= @donation.donation_items.first.quantity %>`);
     }
     
   });
 </script>
   

app/views/donations/create.html.erb
<%= newebpay_donation_pay_button "", "https://cdonate.newebpay.com/npp/2020guarantee", 
  order_number: @donation.id, description: "捐款說明", price: @donation.total_amount, address: @donation.address,
  name: @donation.name, phone: @donation.mobile_phone, payment_methods: [:credit_card, :webatm, :vacc, :barcode, :cvs],
  receipt_address: @donation.address, return_url: "https://2020staging.npp.vote/", id: 'donation' %>






<script language="JavaScript">
  $(document).ready(function () {
    $('#donation').click();
  });
</script>

app/views/donations/edit.html.erb
<%= render 'form', donation: @donation %>

app/views/donations/show.html.erb
<div class="donation-nav">
    <div class="npp-logo"><%= link_to image_tag("npp_logo.png", size: "160x40", alt: "時代力量"), "https://2020staging.npp.vote/"  %></div>
</div>


<div class="donation-wrap">
  <div class="donation">
    <p>捐款項目： <%= @donation.donation_category.name %></p>
    
    <% if @donation.donation_items.present? %>
      <% item = @donation.donation_items.first %>
      <p>品名：<%= item.donation_reward.name %></p>
      <p>數量：<%= item.quantity %></p>
    <% end %>
    
    <p>總金額：<%= @donation.total_amount %></p>
    
    <p>姓名：<%= @donation.name %></p> 
    <p>手機號碼：<%= @donation.mobile_phone %></p>
    <p>地址：<%= @donation.address %></p>
    
    
    <%= link_to  "修改訂單", edit_donation_path(@donation) %>
    <span class="donate-btn">
      <% if @donation.confirmed.blank? %>
        <% "測試 https://cdonate.newebpay.com/npp/2020guarantee" %>
      
        <%= newebpay_donation_pay_button "前往捐款頁面", "https://cdonate.newebpay.com/npp/2020guarantee", 
          order_number: @donation.id, description: "捐款說明", price: @donation.total_amount, address: @donation.address,
          name: @donation.name, phone: @donation.mobile_phone, payment_methods: [:credit_card, :webatm, :vacc, :barcode, :cvs],
          receipt_address: @donation.address, return_url: "https://2020staging.npp.vote/", class: 'btn btn-success', id: 'donation' %>
      
      <% end %>
    </span>
  </div>
</div>